### ISSUE TITLE
Regarding psme-network agent compilation

### ISSUE THREAD

**Issue by askatti** [01org/intelRSD#12]
Hi

We are trying to compile psme-network agent, and it fails due to missing fm10kd-devel package.
In the PSME User Guide, its mentioned that the package is available for fedora but not for Ubuntu.

Can you please help in locating this package for Ubuntu ?

Cmake error reports that a particular header file is missing, hence failing out. Can you please let us know what functionality is required from this package.

Many Thanks
Anand

**Comment by fberndl** [comment]
Hi,

we tried to prepare using cmake on Fedora 23 but cmake is failing to find the header file acl_nl_cmds.h.
![screenshot from 2016-10-19 09-37-34](https://cloud.githubusercontent.com/assets/22743272/19509597/ccfbf836-95df-11e6-8a75-921f123b2d4d.png)

I tested it in a fedora 22 & 23 lxc container and in a virtual box. The compilation process seems to work anyway, there are no errors shown. It would be very interesting, to know the name and how to install this header/package for fedora.

**Comment by maciejro** [comment]
Hi @askatti, @fberndl ,

About @askatti issue – the information that you have read in PSME User Guide is true. There is no corresponding package for Ubuntu so there is no possibility to compile PSME Network Agent on this OS.

About @fberndl  issue – in [PSME User Guide](http://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/psme-user-guide.html) in chapter _2.8 Access Control List (ACL)_ you can find following statement: _“This feature requires relevant ONP Switch Software with ACL support”_. Without such software with all required libraries user will not be able to compile PSME Network Agent.

**Comment by maciejro** [comment]
Hi @askatti, @fberndl,

I'm closing this issue since there is no response for last few days and it looks like my last reply was sufficient.
Feel free to open new issues if you still need any help!

**Comment by askatti** [comment]
Thanks for the reply.
