### ISSUE TITLE
psme-rest-server fails with " Cannot start connector on port 8443: Success"

### ISSUE THREAD

**Issue by fberndl** [01org/intelRSD#13]
Hi,

I used an lxc container with Ubuntu 14.04 amd64, updated to built the binaries, like described in the PSME User Guide v1.2 . My target system is also Ubuntu 14.04 amd64, updated.  I have used the `psme-gen-serv-cert.sh` script to generate certificates. The problem is that the psme-rest-server fails to start because connactor cannot be started:

`/usr/bin$ sudo ./psme-rest-server /etc/psme/psme-rest-server-configuration.json `

Results in this error: 
`2016-10-31 14:27:49.641298098 - ERROR - app - [application-ref/src/app.cpp:run:163] Cannot start connector on port 8443: Success`

This looks for me similar to some issue in #4 ,  but the solution to use "setenv.sh && build64.sh" didn't work for me.

During build process the libmicrohttp.so is found:
```
-- Threads: 
-- Found CURL: /usr/include  
-- CURL header: /usr/include
-- CURL lib   : /usr/lib/x86_64-linux-gnu/libcurl.so
-- Found mhd: /usr/include  
-- MHD header: /usr/include
-- MHD lib   : /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
-- Could NOT find Boost
-- Found doxygen: /usr/bin/doxygen
-- Configuring done
-- Generating done
```

[psme-rest-server-configuration.txt](https://github.com/01org/intelRSD/files/561855/psme-rest-server-configuration.txt)
[certifcate_generation_log.txt](https://github.com/01org/intelRSD/files/561837/certifcate_generation_log.txt)
[ldd_psme_rest_server.txt](https://github.com/01org/intelRSD/files/561838/ldd_psme_rest_server.txt)
[psme_rest_server.txt](https://github.com/01org/intelRSD/files/561839/psme_rest_server.txt)

[ldd_libmicrohttpd.so.10.txt](https://github.com/01org/intelRSD/files/561864/ldd_libmicrohttpd.so.10.txt)

**Comment by maciejro** [comment]
Hi @fberndl,

We're currently looking at your issue and give you a response as soon as we can.

**Comment by maciejro** [comment]
Hi @fberndl,

First of all sorry for a delayed response. We've investigated your problem and it looks like you are using the old version (*.26*) of `libgnutls` library. The **minimum** required version of this library is ***.28*** which supports `TLS_ECDHE_ECDSA_AES_128_GCM_SHA256` cipher required by PSME REST Server. 

Please update this library in your OS and try again.

**Comment by fberndl** [comment]
Hi,
this library wasn't installed during the installation process at my build container, after installing gnutls28 it was still compiled using .so.26, so I manually set the .so link to .so.28
```
sudo apt-get install libgnutls28
sudo ln -s libgnutls.so.28.30.1 libgnutls.so
```

Thanks for help, the psme-rest-server is now starting. I will verify communication and close this ticket afterwards

**Comment by fberndl** [comment]
Hi @maciejro ,

I could verify the communication  (psme-rest-server and psme-compute-simulator) to the PODM  using following command:

`curl https://10.8.0.120:8443/redfish/v1/Systems/1 --insecure --user admin:admin`

Thanks for your support.

**Comment by maciejro** [comment]
Hi @fberndl,

I'm glad to hear that! You're welcome!
