### ISSUE TITLE
psme network agent udev issues

### ISSUE THREAD

**Issue by askatti** [01org/intelRSD#15]
Hi 

We are seeing some issues with network agent code: can you please help us with these queries ? 
1.  We are seeing that all the udev APIs in sysfs.cpp fails when we run the network agent on ubuntu 14.
2. Also the netlink socket calls are not going through.

Thanks
Anand

**Comment by tbykowsk** [comment]
Hi @askatti,

The PSME Network Agent reference code was created for the Bulldog Creek SDV hardware. The FM10000 switch used in that configuration runs on the Fedora-based OS (the Intel Open Network Platform Switch Platform https://github.com/01org/intelRSD/issues/12#issuecomment-254793202). Therefore, some functionalities of the Network Agent may not be compatible with Ubuntu.

**Comment by askatti** [comment]
Many Thanks @tbykowsk.

Few more queries>
1. Which version of libudev is being used in Fedora OS on which it works  ? 
2.  Also, I see there are referenecs to DCRP API and daemon. Could you please elaborate why its required and how i could get access to DCRP daemon code ? 
3. Most of the APIs in the network code talks to netlink layer. Could you please confirm if you have a custom netlink module (server) implemented to serve those APIs?

Thansk
Anand

**Comment by tbykowsk** [comment]
You are welcome @askatti,

1. Libudev version is 222, the Fedora OS version is 23.
2. The reference PSME Network Agent is implemented for the SDV switch and requires proprietary API which is delivered to Intel Switch customers only.
3. Yes, it is configured as you described.

**Comment by askatti** [comment]
Hi @tbykowsk.

Requesting you to kindly clarify these two more queries.

1.  Could you please help me in understanding code snippet (is_member_port and PortClass::Logical)  at line no. 226 and 230 in [file](https://github.com/01org/intelRSD/blob/master/PSME/agent/network/src/hw/fm10000/network_controller.cpp) ?  

- [ ]  Why we need to skip if its a member port and if its a logical port  
  

- [ ]  by the way what is a member port?

- [ ] Due to these two "condition check" vlan ports will not be added to portvlan model.

2. In the code, only port_vlan_manager is used, but vlan_manager is not being used. What is their functionality and when to use which one ? 

Thanks
Anand

**Comment by pperycz** [comment]
Hi @askatti, @tbykowsk is unavailable right now so I'll try to provide you with some answers:

In general: a physical port can be a part of LAG (logical aggregated port) - in code such LAG is represented by Logical Port class. Single Logical Port usually consists of few physical Ports. 

A physical port can have VLANs only if it is not a part of any Logical Port. Logical Port can have VLANs only if it is not empty (has at least one Port member).

Concerning the mentioned code snippet:

> Why we need to skip if its a member port and if its a logical port?

We skip it only if selected Port is a part of Logical Port (then Logical Port should have VLANs) or selected Port is an empty Logical Port (without members, broken one)

> by the way what is a member port?

Member Port is a Port which is a part of LAG.

> Due to these two "condition check" vlan ports will not be added to portvlan model.

Yes, this is correct.  VLAN Port will be added only if this is a proper physical Port which is not a member of LAG or it is a proper Logical Port (LAG).

> In the code, only port_vlan_manager is used, but vlan_manager is not being used. What is their functionality and when to use which one?

PortVlanManager is an alias for `GenericManager<model::EthernetSwitchPortVlan>` and
VlanManager is an alias for `GenericManager<model::Vlan>`. First one is used to manage EthernetSwitchPortVlan objects, second to manage Vlan objects.

Hope that helps!

**Comment by Vishesh-GIT** [comment]
Hi @tbykowsk @pperycz 

@pperycz : thanks for the reply on our last query.

we are running VTS on north bound of AMC and observing following error message in the report.csv.
VTS is trying to set Link speed to a value which is out of range and error got thrown by AMC on validating against the schema as TypeError which ultimately resulting into invalid payload error with http status code 400. this status code 400 is not part of the acceptable status code list. we are observing such kind of error message for few other attributes also. here we want to take your input like can we consider this as test passed or should we change in implementation so that such error reports are avoided. if change in implementation is preferred, then should it be in VTS or in AMC code. Also we would like to know how VTS is reporting in your testing environment. VTS report from our testing has been attached as well (renamed to .txt). if you could point out any other error in the report please let us know. thanks in advance.

[report.csv.txt](https://github.com/01org/intelRSD/files/710352/report.csv.txt)

> Patch https://192.168.10.155:8443/redfish/v1/EthernetSwitches/1/Ports/38
>         request parameters {
>                 headers: {'Content-Type': 'application/json'}
>                 data: {"LinkSpeedMbps": -9223372036854775808}
>                 verify: False
>         }
> 
>         response
>                 {
>                     "error": {
>                         "@Message.ExtendedInfo": [
>                             "LinkSpeedMbps is not valid type uint."
>                         ],
>                         "message": "Request payload is invalid or missing",
>                         "code": "InvalidPayload"
>                     }
>                 }
> 
> 
>         STATUS_CODE: 400, ACCEPTABLE: [200, 204, 405, 422, 501]
> 
> 
>         [WARNING] - Patch https://192.168.10.155:8443/redfish/v1/EthernetSwitches/1/Ports/38
> 
>

**Comment by maciejro** [comment]
Hi @Vishesh-GIT,

First of all, sorry for a delayed response. Here are our answers to your questions.

> can we consider this as test passed or should we change in implementation so that such error reports are avoided.

When VTS reports a warning it usually depends on specific circumstances if a given test should be considered as failed.
In this case the metadata specifies Int64 type as LinkSpeedMbps and VTS tests it by setting a negative value. In our internal testing environment such request will also yield HTTP 400 code and we consider this warning reasonable and the test passed.

> If you could point out any other error in the report please let us know. thanks in advance.

There is nothing more to worry about :)

**Comment by maciejro** [comment]
Hi @Vishesh-GIT,

It's been 18 days since my last response. Is there anything more that we can help?

If not than I'll close this issue tomorrow. However feel free to answer in this topic or open a new one if needed.

**Comment by Vishesh-GIT** [comment]
@maciejro 

thank for clarifying all our queries. we don't have more further query related to this topic. so this issue can be closed. we do have few queries regarding node composition. we doing some analysis from our side. if any information required, will ask in new issue. thanks for all your support.
