### ISSUE TITLE
Error when compiling PSME on Fedora 20

### ISSUE THREAD

**Issue by angocor** [01org/intelRSD#17]
Hello.

When trying to compile PSME on Fedora 20, I get the following error:

![image](https://cloud.githubusercontent.com/assets/7471522/22490402/bec068f6-e7e2-11e6-8938-2ee5960596db.png)

Any help to solve this would be appreciated. Thanks.

**Comment by tbykowsk** [comment]
Hi @angocor,

What compiler do you use? Maybe it does not support the C++11 standard.
Please update your compiler and let me know if it helps.

**Comment by Vishesh-GIT** [comment]
@angocor  
i had similar issue when i had lower version of g++, jsoncpp, jsoncpp-devel and cmake as well.
gcc and g++ >= 4.9.2 , cmake >= 3.0.2 and jsoncpp 0.6 are necessary

**Comment by angocor** [comment]
Thanks for your help and sorry for my late reply. I decided to switch to a newer version of Fedora and therefore I was able to compile it. Thanks.

**Comment by maciejro** [comment]
Hi @angocor,

We're glad we could help you! I'll close this issue then however feel free to open a new one as needed.
