### ISSUE TITLE
PSME configuration issue

### ISSUE THREAD

**Issue by toimcio** [01org/intelRSD#19]
Hi,
We have been trying to get a demo virtual environment of RSD running and I might be missing something, but we have run into some issues. Having set up POD Manager and RMM we moved on to a PSME server with a few agents. As I used the standard setting with RMM distributing the certificates I ran into Exception -32601: METHOD_NOT_FOUND which I assumed, perhaps wrongfully, is caused by the fact that I have relied on the stub for the HAL driver without implementing anything on my own. 
Hence, I opted for a configuration without an RMM and I placed the PODM certificate in /etc/psme/certs manually. However, for some reason the PSME certificate (server.cert and server.key) does not get generated automatically. Since I also had to create the /etc/psme manually, I assume something went wrong with the building/installation process but I have followed the documentation carefully. I am quite confused as to what the real problem might be. Could you advise?

**Comment by tbykowsk** [comment]
Hi @toimcio,

The exception METHOD_NOT_FOUND appears when PSME Rest Server calls a method, which is not implemented in Agents. This error may be ignored if it does not affect any functionality which you require.

The documentation in a few places assumes that PSME Rest Server and Agents are managed as systemd/init services, which provide some additional automation. The PSME Rest Server service in our test environment generates certificates using [psme-gen-serv-cert.sh](https://github.com/01org/intelRSD/blob/master/PSME/lui/OS/rootfs/usr/bin/psme-gen-serv-cert.sh) script:
`./psme-gen-serv-cert.sh --srv-cert=/etc/psme/certs/server.crt --srv-key=/etc/psme/certs/server.key `.
The proposed default directory for certificates is `/etc/psme/certs`, but it can be modified in [the configuration file](https://github.com/01org/intelRSD/blob/master/PSME/application-ref/configuration.json#L7). The directory should be created manually before starting PSME.
Thank you for pointing out these gaps.

**Comment by toimcio** [comment]
Thank you that was most helpful. I have one more follow-up question regarding the first issue. I assume I misconfigured the chassis agent then. Documentation says that "server": "port" field in the chassis/configuration.json file must be the same as configured in PSME rest server. Which field in rest server's configuration does this correspond to? (I tried looking for the default value but the is no match)

**Comment by tbykowsk** [comment]
Field `"server":"port"` needs to be unique for each Agent connected to a given Rest Server.
Fields `"registration":"ipv4"` and `"registration":"port"` in Agents' configuration should match those from Rest Server configuration.  

The exception METHOD_NOT_FOUND rather appears when an Agent have already registered in Rest Server and communication is established, but Rest Server calls a method which is not implemented in the Agent.

**Comment by toimcio** [comment]
I see. I was referring to Table 13 (chapter 7.5.2) in PSME user guide, where the field is described as "Must be  the same as configured in PSME REST Server." Does this mean the aforementioned configuration in REST Server is performed during registration i.e. automatically?

**Comment by tbykowsk** [comment]
A manual configuration is not required, only fields `"registration":"ipv4"` and `"registration":"port"` must match. Agents during registration automatically send to the Rest Server which IP/port should be used for further communication.

The Chassis Agent and the Rest Server do not need to run on the same machine. You may add the field `"server": "ipv4"` in the Agent configuration file . For example:
```
"server" : {
        "ipv4": "1.2.3.4",
        "port": 7780
}
```

**Comment by toimcio** [comment]
That clears things up. Thank you

**Comment by gbhure** [comment]
I do not find psme-gen-serv-cert.sh
Also PSME certificate (server.cert and server.key) does not get generated automatically. Anybody faced this issue? I get below msges

```
2019-11-06 12:09:48.954615549 - INFO  - rest - Starting connector listening on <ip>:8443 (wlo1)
2019-11-06 12:09:48.954650955 - INFO  - rest - Waiting for CA certificate...
2019-11-06 12:09:50.954783601 - INFO  - rest - Waiting for CA certificate...
2019-11-06 12:09:52.954909252 - INFO  - rest - Waiting for CA certificate...
```
