### ISSUE TITLE
secured communication between PODM and PSME

### ISSUE THREAD

**Issue by Vishesh-GIT** [01org/intelRSD#20]
Hi,

we have PODM and PSME up and running. north bound of PSME and south bound of PODM are secured with CA certificated as per the instruction in PODM user guide chapter 7. we don't have RMM in our setup so as per the user guide manually all relevant cert and key files are manually copied to their respective places. pod-manager-certificate-creation.sh script was used to generate these cert and key file and updated the jks file in path /var/lib/pod-manager . took back up of generated cert and files as well as client.jks and keystore.jks file for future use. then PODM application was re-installed and PSME kept running as it is or restarted the PSME services, in both the cases , secure connection between PODM and PSME is failling. PSME reports "No certificate file unavailable" error message. previously generated certificate file and key were kept in their respective place and expected that secured connection remain in tact. question is, does it required to run the pod-manager-certificate-creation.sh script every time on re-installation of PODM. what is the dependency here.? if there is set of certificate file and keystore generated once and it should be able to use same set across multiple re-installation instance and secure connection between PODM and PSME should be in tact.

**Comment by maciejro** [comment]
Hi @Vishesh-GIT,

Please correct me if I am wrong, but your scenario is:

1) Installation of PODM via `*.deb` package
2) Installation of PSME
3) Generating certficate via `pod-manager-certificate-creation.sh` script
4) Update `*.jks` file
5) Copy certficate to PSME
6) Configure PSME to work without RMM and use copied certificate
7) Run PODM and PSME
8) Everything works correctly - there is no issue in communication between PODM & PSME 
9) Stop PODM, but PSME is still running
10) Reinstall PODM with `*.deb` package
11) Start PODM
12) No connection between PODM & PSME

PODM will replace `*.jks` file and other files in `/var/lib/pod-manager` directory during (re)installation process. If you would like to preserve your cert and key files, put them in `SW/pod-manager/os-package/contents/var/lib/pod-manager` prior to building new `*.deb`  file.

Please let us know if this resolves your issue!

Could you also attach logs from PSME? We're not able to find anything like 
> No certificate file unavailable

in our code.

**Comment by Vishesh-GIT** [comment]
@maciejro 

sorry, the error message that was observed "Failed to verify certificate: No certificate was found" originated from file application-ref/src/rest-ref/server/connector/microhttpd/mhd_ssl_connector.cpp: verify_certificate function.

about steps you mentioned is what i followed. small change in that step is that, after step 10, that is re-installation of PODM with *.deb package, i copied back the previously generated certificate and key files and client.jks keystore files. then PODM was restarted and there was no secured connection.

As you suggested, let me try building the deb package keeping the certificate and key files in the path as you mentioned about and test this scenario again.

Thanks for your input

**Comment by maciejro** [comment]
Hi @Vishesh-GIT,

We've managed to reproduce your issue. If you have used `pod-manager-certificate-creation.sh` script then you have to make a copy of files `/var/lib/pod-manager/ca/root.crt` (mentioned in ***Chapter 7.4.3 CA certificate distribution*** in _PODM User Guide_) and `/var/lib/pod-manager/client.jks` files. After reinstall just copy those files to (respectively)  `/var/lib/pod-manager/root.crt` and `/var/lib/pod-manager/client.jks`

Hope that this will resolve your issue!

If this problem still exists then provide us even more detailed steps to follow.

**Comment by Vishesh-GIT** [comment]
@maciejro 

probably i had missed to restore client.jks file last time. now able to re-establish secured connection across re-installation of PODM. thanks for your help. i am closing this ticket
