### ISSUE TITLE
VLAN creation on node composition with Ethernet interface

### ISSUE THREAD

**Issue by Vishesh-GIT** [01org/intelRSD#21]
Hi,

we tried to do node composition with Ethernet interface requirement specified in the json template as given in the podm api specification guide. node composition was successful. log shows neighbor mac of switch port and the mac address of Ethernet interface of the selected compute node are matching. here we need some understanding about the behavior observed. there was primary Vlan and list of Vlan fields specified in the template. are those Vlans expected to be created as part of node composition command execution or should those Vlan's to be created manually prior to node composition command execution. in our case, vlan was not created prior to node composition and after successful node composition also no Vlan's were created. let us know that the observed behavior is as expected? does the node composition creates the Vlans given in the requirement json template?

**Comment by maciejro** [comment]
Hi @Vishesh-GIT,

PODM creates VLANs during assembly process (triggered by `/Actions/#ComposedNode.Assemble` REST API request for a Composed Node), so requested VLANs may not be present immediately after successful allocation. Please check if all requested VLANs were created after performing `/Actions/#ComposedNode.Assemble` request – if not, please attach PODM & PSME logs to your next reply in this topic.

When allocating Composed Node with VLAN requirements, creating VLANs first is an unnecessary step. During assembly process all existing VLANs (except the reserved and requested ones) are deleted and PODM ensures that all user-requested VLANs are created (or preserved if were already present).

**Comment by Vishesh-GIT** [comment]
@maciejro 
Thanks for your input, we are able to verify VLAN creation on composing node with EthernetInterface requirement. so closing this ticket
