### ISSUE TITLE
Confusion about the composed node

### ISSUE THREAD

**Issue by hz19900424** [01org/intelRSD#22]
Hello, I am confused about the "Composed Node"
- According to the API, "Composed Node" seems just like resource Virtual Machine, but it is obvious not, because virtualization can not be conducted on bare metal.
- I noticed that the pod-manager-api-specification said that:
> Currently a user can request allocation of a single node with a single request. Node components--CPU,memory,local storage,network interface--must be located on a single physical blade. Remote storage can be located anywhere in the Pod.

Then I got the following questions:
1. Is it possible to compose more than one node on a single physical server, if it is, how dose it be implemented, if not, there is no limitations mentioned on API specification.
2. If composing a node is just marking the resource(Allocate) and specifying the boot source(Assemble), dose it make any sense? Is there any supposed usage scenario or is there any existing use case.
3. Is there any further plan to break these hardware limitations and make Composed Node more flexible, and how?

**Comment by maciejro** [comment]
Hi @hz19900424,

Here are answers to your questions:

> 1. Is it possible to compose more than one node on a single physical server, if it is, how dose it be implemented, if not, there is no limitations mentioned on API specification.

Currently it is not possible to compose more than one node using the same physical server / blade (represented by Redfish ComputerSystem). Also using more than one ComputerSystem to create a single Composed Node is not supported.

> 2. If composing a node is just marking the resource(Allocate) and specifying the boot source(Assemble), dose it make any sense? Is there any supposed usage scenario or is there any existing use case.

There are more composition possibilities – e.g. user can request VLANs creation for created nodes, request creation of remote drives from a Master drive, etc. More information can be found in **Chapter 4.11 Composed node collection** of  [POD Manager API Specification](https://01.org/sites/default/files/documentation/pod-manager-api-specification_0.pdf).


> 3. Is there any further plan to break these hardware limitations and make Composed Node more flexible, and how?

Please check our [official Rack Scale Design page on 01.org website](https://01.org/intelRSD) for more information about upcoming plans!


If you still have any question, feel free to ask them!
