### ISSUE TITLE
How to create an bootable iSCSI target with Linux as Operating System?

### ISSUE THREAD

**Issue by fberndl** [01org/intelRSD#26]
Hi,

how can we create an bootable iSCSI target with Linux as Operating System? 
We followed the steps in the PSME User Guide but we stuck at step 5 in chapter 5.3.2.2 

5.3.2.2 Creation of LVM structure

`dd if=your_image.raw of=/dev/main_volume_group/base_logical_volume`

I copied an ubuntu server iso to the iscsi target, the installation process fails because it searches the drivers on a CDROM..

How is this intended to be done?

**Comment by tbykowsk** [comment]
Hi @fberndl,

The base logical volume is intended to store an Operating System which is ready to boot from iSCSI.

An example how you may create it:
1. Install Ubuntu 16.04 Server on a VM (in BIOS Legacy mode for remote booting via iPXE, or UEFI mode for iSCSI Out of Band)
2. Start the VM and switch in it to a root account
3. Install packages for iSCSI:
`apt-get install open-iscsi initramfs-tools`
4. Include iSCSI in list of modules:
`echo "iscsi" >> /etc/initramfs-tools/modules`
5. Enable automatic iSCSI connection in initramfs:
`echo "ISCSI_AUTO=true" > /etc/iscsi/iscsi.initramfs`
6. Run initramfs update:
`update-initramfs -u`
7. Shutdown the VM and convert it to a raw format image
8. Copy the image to your base logical volume

Depending on your hardware, you may also want to configure system's terminals to use Linux Serial Console.

Please let me know if you have any further questions.

**Comment by fberndl** [comment]
I think there is the network configuration of initramfs is missing in the example? I configured the psme-storage portal interface to use the storage management/access vlan 4093. However, the boot fails because iscsistart can't connect to the target. 

`iscsistart: Connection-1:0 to [target: iqn.2017-07.wien.datacom.testnet:ubuntu_base_target, portal 10.2.0.3,3260] trough [iface: default] is shutdown
iscsistart: initiator reported error (8 -  connection timed out)
done.`

Thanks for your support

**Comment by tbykowsk** [comment]
A custom network configuration of initramfs should not be necessary. However, your hardware may require some additional setup.

A system while booting should receive an IP address from PODM's DHCP server, read iSCSI target parameters from iBFT and then attempt to establish a connection to the target. Ubuntu by default should try it on all interfaces. The storage management/access vlan 4093 on the node's interface needs to be untagged.

Could you try to copy the system raw image to the node's local drive, boot from it, and then manually attempt to connect to the iSCSI target on Storage Services (using isciadm)? It should be able to establish connection.

**Comment by fberndl** [comment]
The problem was that I configured the network switch for tagged vlan 4093. I reconfigured it to untagged and it works fine now. Thanks for your fast and very good support.

**Comment by AndyCCChang** [comment]
Hi @tbykowsk,
Could you provide detailed information about how to convert the VM to a raw format image?
(7. Shutdown the VM and convert it to a raw format image)


Thank you.
Andy

**Comment by tbykowsk** [comment]
Hi @AndyCCChang ,

VirtualBox CLI provides a way to convert VDI disk image to the raw format:
`VBoxManage clonehd sdb.vdi sdb.raw --format RAW`

**Comment by AndyCCChang** [comment]
Hi @fberndl ,
Could I know what version of Ubuntu 16.04 you used? Was Ubuntu 16.04.3 server or anything else?

Thanks.
Andy
