### ISSUE TITLE
Why is initatior-name is set to ALL in the targets config file?

### ISSUE THREAD

**Issue by fberndl** [01org/intelRSD#28]
Hi, 

I have seen that the initator-**name** is set to "ALL" in the targets config file. From the manpage

```
initiator-address <addr>
    Allows connections only from the specified IP address. Defaults to ALL if no initiator-address directive is specified. 

initiator-name <addr>
    Allows connections only from the specified initiator name. 
```

This configuration seems to be wrong. I didn't find a section in the code where initiator-**name** is set to ALL. I could only  find the initator-**address** which is set to ALL. Do you know why this could happen? 

This issue blocks iscsi target discovery (Ubuntu 16.04) using iscsiadm (open-iscsi, command: iscsiadm -m discovery -t st -p <psme_portal_ip>). Discovery works if I delete this line manually on the storage node in the targets config file. 

I tested it with rsdv1 and debian jessie

**Comment by tbykowsk** [comment]
Hi @fberndl,

In previous versions POD Manager set the initiator-name to "ALL" during assembly.  It was modified in 2.1.3 release and by default the initiator-name should no longer be set. You could also change this in older versions of POD Manager by replacing ["ALL"](https://github.com/01org/intelRSD/blob/update-to-latest-sources-december-2016/PODM/SW/pod-manager/podm-assembly/src/main/java/com/intel/podm/assembly/tasks/NewRemoteDriveAssemblyTask.java#L152) with an empty string "".

Alternatively, you may enable discovery of targets with initiator-name set to "ALL" in Ubuntu by putting `InitiatorName=ALL` in `/etc/iscsi/initiatorname.iscsi` file and restarting iscsid service.

**Comment by fberndl** [comment]
Thanks for support, that clarify the problem and the workaround works fine.
