### ISSUE TITLE
Error: Redefinition of struct i2c_msg

### ISSUE THREAD

**Issue by mmnelemane** [01org/intelRSD#6]
Following error occurred while building PSME :

[  6%] Built target logger_example_streams
[  6%] Built target logger_example_udp_receiving
[  6%] Building C object common/pca95xx/CMakeFiles/pca95xx.dir/src/pca95xx_i2c.c.o
In file included from /tmp/intelRSD/PSME/common/pca95xx/src/pca95xx_i2c.c:34:0:
/usr/include/linux/i2c-dev.h:37:8: error: redefinition of ‘struct i2c_msg’
 struct i2c_msg {
        ^
compilation terminated due to -Wfatal-errors.
common/pca95xx/CMakeFiles/pca95xx.dir/build.make:103: recipe for target 'common/pca95xx/CMakeFiles/pca95xx.dir/src/pca95xx_i2c.c.o' failed
make[2]: *** [common/pca95xx/CMakeFiles/pca95xx.dir/src/pca95xx_i2c.c.o] Error 1
CMakeFiles/Makefile2:1167: recipe for target 'common/pca95xx/CMakeFiles/pca95xx.dir/all' failed
make[1]: *** [common/pca95xx/CMakeFiles/pca95xx.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

This could be a platform specific issue while building on SLE 12 SP1. But I haven't tried to reproduce it in other platforms.

**Comment by maciejro** [comment]
Hi @mmnelemane,

Could you provide exact steps how are you compiling our solution? Which commands and in which directories are you executing them?

Also which compiler are you using?

**Comment by maciejro** [comment]
Hi @mmnelemane,

Is there anything that we can help? If you still encounter this problem please give us a notice. Otherwise I'll close this issue tomorrow morning.

**Comment by maciejro** [comment]
Since there is no more response for last 21 days I will close this issue
